### ISSUE TITLE
Docs for 2.0

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/TimeseriesSurrogates.jl#44]
Just an issue to keep track of what needs to be in the documentation for the 2.0 release (#39):

- [x] Go back to Documenter.jl (no more mkdocs)
- [x] Each surrogate method needs a statement about what properties of the original signal it preserves.
- [x] Plot recipe should accept multiple surrogates (#40). *Not necessary*. The user can easily add surrogates to the relevant subplot after calling `surroplot`.
- [x] Fix transparency of histograms (#40). Need to decide on what to include here. 
- [x] Make sure all references are properly cited. It seems that Documenter now lists repeated references at the bottom of the page. This can be solved manually by not using the [^ref] syntax and manually putting the references in relevant places. It would be nice to do this automatically, though. *This seems to be a documenter issue, and should not stop the 1.0 release.*
- [x] A short note in each method docstring stating whether the surrogate method yields _constrained_ surrogate realizations (some sort of shuffling of the original values) or _typical_ surrogate realizations (model-based, directly or indirectly fit some model to the data, then use that data-informed model to generate surrogates).
- [x] Generate all images/gifs with Documenter instead of manually uploading.
- [x] The plot_and_anim.jl page is not necessary. Reproducing these plots is done by the user in very few lines of code. Should be removed.
- [x] All methods should be briefly described on their own page, including a nice plot for a suitable time series. This is a good place to state caveats and potential issues with any methods (see for example #45). *We'll keep the docstrings as the main place for info*, examples can go elsewhere.

@Datseris Feel free to add things here if I've forgotten something or tick of when done.
